version: '3.6'


services:
  db-server:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yourpassword123
  boilerplate-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=Heroes;User=sa;Password=Yourpassword123;TrustServerCertificate=True;Encrypt=false
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev