name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print info
      run: |
        echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build WebApiBoilerplate.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test WebApiBoilerplate.sln --configuration Release
